import { t, getLocale } from "./i18n";
import { useState, type FormEvent } from "react";
import { Folder, FolderPlus, Files, FileText, Search, Plus, ArrowRight, Trash2, Pencil, X } from "lucide-react";
import type { DocumentFolder, VeritasDocument } from "./types";
import { ApiError } from "./api";

type Props = {
  documents: VeritasDocument[]; folders: DocumentFolder[];
  onOpen: (document: VeritasDocument) => Promise<void>;
  onCreate: (title: string, folderId: string | null) => Promise<void>;
  onDelete: (document: VeritasDocument) => Promise<void>;
  onMove: (document: VeritasDocument, folderId: string | null) => Promise<void>;
  onFolderSave: (name: string, id?: string) => Promise<DocumentFolder>;
  onFolderDelete: (folder: DocumentFolder) => Promise<void>;
};
const date = (value: string) => new Intl.DateTimeFormat(getLocale(), { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value));
export default function DocumentsWorkspace({ documents, folders, onOpen, onCreate, onDelete, onMove, onFolderSave, onFolderDelete }: Props) {
  const [selected, setSelected] = useState("all"); const [search, setSearch] = useState(""); const [creating, setCreating] = useState(false); const [title, setTitle] = useState(""); const [newFolderId, setNewFolderId] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<VeritasDocument | null>(null);
  const [folderForm, setFolderForm] = useState<{ id?: string; name: string } | null>(null);
  const [folderDeleting, setFolderDeleting] = useState<DocumentFolder | null>(null);
  const perform = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : t("No se pudo completar la operación.")); } finally { setBusy(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); void perform(async () => { await onCreate(title.trim() || t("Documento sin título"), newFolderId || null); setCreating(false); setTitle(""); }); };
  const visible = documents.filter(document => (selected === "all" || selected === "unfiled" ? selected === "all" || !document.folder_id : document.folder_id === selected) && document.title.toLocaleLowerCase(getLocale()).includes(search.toLocaleLowerCase(getLocale())));
  const currentFolder = folders.find(folder => folder.id === selected);
  const totalWords = documents.reduce((sum, document) => sum + document.word_count, 0);
  const sealed = documents.reduce((sum, document) => sum + (document.versions_count ?? 0), 0);
  const modal = (heading: string, content: React.ReactNode, close: () => void) => <div className="modal-backdrop" role="presentation" onMouseDown={event => { if (!busy && event.target === event.currentTarget) close(); }}><section className="modal" role="dialog" aria-modal="true" aria-label={heading}><button className="modal-close" aria-label={t("Cerrar")} disabled={busy} onClick={close}><X size={18}/></button><h2>{heading}</h2>{content}{error && <p className="form-error" role="alert">{error}</p>}</section></div>;
  return <main className="workspace dashboard archive-workspace">
    <section className="dashboard-head"><div><p className="eyebrow">{t("Archivo personal")}</p><h1>{t("Mis documentos")}</h1><p>{t("Un espacio para escribir, organizar y conservar la memoria de tus textos.")}</p></div><button className="primary" onClick={() => { setCreating(true); setNewFolderId(currentFolder?.id ?? ""); setError(""); }}><Plus size={18}/>{t("Nuevo documento")}</button></section>
    <section className="summary-strip" aria-label={t("Resumen")}><div><strong>{documents.length}</strong><span>{t("documentos")}</span></div><div><strong>{sealed}</strong><span>{t("versiones certificadas")}</span></div><div><strong>{totalWords.toLocaleString(getLocale())}</strong><span>{t("palabras conservadas")}</span></div><div className="summary-note"><span className="seal-mini">V</span><p><strong>{t("Tu archivo es privado.")}</strong><br/>{t("Tú decides qué versiones compartes.")}</p></div></section>
    <div className="archive-grid">
      <aside className="folder-sidebar"><header><span>{t("CARPETAS")}</span><button aria-label={t("Nueva carpeta")} title={t("Nueva carpeta")} onClick={() => { setFolderForm({ name: "" }); setError(""); }}><FolderPlus size={18}/></button></header>
        <button className={selected === "all" ? "active" : ""} onClick={() => setSelected("all")}><Files size={17}/><span>{t("Todos los textos")}</span><small>{documents.length}</small></button>
        <button className={selected === "unfiled" ? "active" : ""} onClick={() => setSelected("unfiled")}><FileText size={17}/><span>{t("Sin carpeta")}</span><small>{documents.filter(document => !document.folder_id).length}</small></button>
        <div className="folder-divider"/>{folders.map(folder => <button key={folder.id} className={selected === folder.id ? "active" : ""} onClick={() => setSelected(folder.id)}><Folder size={17}/><span>{folder.name}</span><small>{documents.filter(document => document.folder_id === folder.id).length}</small></button>)}
        <button className="new-folder-link" onClick={() => { setFolderForm({ name: "" }); setError(""); }}><Plus size={15}/><span>{t("Nueva carpeta")}</span></button>
      </aside>
      <section className="archive-content"><header className="archive-content-head"><h2>{currentFolder?.name ?? (selected === "unfiled" ? t("Sin carpeta") : t("Todos los textos"))}</h2>{currentFolder && <div className="folder-actions"><button aria-label={t("Renombrar carpeta")} title={t("Renombrar carpeta")} onClick={() => { setFolderForm(currentFolder); setError(""); }}><Pencil size={16}/></button><button aria-label={t("Eliminar carpeta")} title={t("Eliminar carpeta")} onClick={() => { setFolderDeleting(currentFolder); setError(""); }}><Trash2 size={16}/></button></div>}<label className="archive-search"><Search size={16}/><input aria-label={t("Buscar documentos")} placeholder={t("Buscar por título…")} value={search} onChange={event => setSearch(event.target.value)}/></label></header>
        {error && !deleting && !folderForm && !folderDeleting && <p className="form-error" role="alert">{error}</p>}
        {creating && <form className="new-document" onSubmit={submit}><label htmlFor="new-title">{t("Título del nuevo documento")}</label><input id="new-title" value={title} onChange={event => setTitle(event.target.value)} autoFocus placeholder={t("Por ejemplo, Notas para un ensayo")}/><select aria-label={t("Carpeta del nuevo documento")} value={newFolderId} onChange={event => setNewFolderId(event.target.value)}><option value="">{t("Sin carpeta")}</option>{folders.map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><button className="primary" disabled={busy}>{busy ? t("Creando…") : t("Crear y escribir")}</button><button type="button" className="secondary" disabled={busy} onClick={() => setCreating(false)}>{t("Cancelar")}</button></form>}
        <div className="archive-list-head"><span>{t("Documento")}</span><span>{t("Carpeta")}</span><span>{t("Último cambio")}</span><span/></div>
        {visible.map(document => <div className="archive-row" key={document.id}><button className="archive-open" disabled={busy} onClick={() => void perform(() => onOpen(document))}><span className="doc-icon">{document.versions_count ? "V" : <FileText size={20}/>}</span><span><strong>{document.title}</strong><small>{t("{count} palabras · {sessions} sesiones", { count: document.word_count, sessions: document.sessions_count ?? 0 })}{document.versions_count ? t(" · {count} selladas", { count: document.versions_count }) : ""}</small></span><ArrowRight size={18}/></button><select aria-label={t("Mover {title} a una carpeta", { title: document.title })} value={document.folder_id ?? ""} disabled={busy} onChange={event => void perform(() => onMove(document, event.target.value || null))}><option value="">{t("Sin carpeta")}</option>{folders.map(folder => <option key={folder.id} value={folder.id}>{folder.name}</option>)}</select><span className="date-cell">{date(document.updated_at)}</span><button className="document-delete" aria-label={t("Eliminar {title}", { title: document.title })} title={t("Eliminar documento")} onClick={() => { setDeleting(document); setError(""); }}><Trash2 size={16}/></button></div>)}
        {!visible.length && <div className="archive-empty"><FileText size={32}/><h3>{search ? t("No hay textos con ese título") : t("Esta carpeta está lista para tus textos")}</h3><p>{search ? t("Prueba otra búsqueda.") : t("Crea un documento o mueve aquí alguno de tu archivo.")}</p></div>}
      </section>
    </div>
    {deleting && modal(t("Eliminar documento"), <><p>{t("Vas a eliminar")} <strong>«{deleting.title}»</strong> {t("y todo su historial, incluidas sus versiones certificadas. Esta acción no se puede deshacer.")}</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={() => setDeleting(null)}>{t("Cancelar")}</button><button className="danger" disabled={busy} onClick={() => void perform(async () => { await onDelete(deleting); setDeleting(null); })}>{busy ? t("Eliminando…") : t("Eliminar definitivamente")}</button></div></>, () => setDeleting(null))}
    {folderForm && modal(folderForm.id ? t("Renombrar carpeta") : t("Nueva carpeta"), <form className="folder-form" onSubmit={event => { event.preventDefault(); void perform(async () => { const saved = await onFolderSave(folderForm.name.trim(), folderForm.id); setSelected(saved.id); setFolderForm(null); }); }}><label>{t("Nombre de la carpeta")}<input required maxLength={100} autoFocus value={folderForm.name} onChange={event => setFolderForm({ ...folderForm, name: event.target.value })}/></label><div className="modal-actions"><button type="button" className="secondary" disabled={busy} onClick={() => setFolderForm(null)}>{t("Cancelar")}</button><button className="primary" disabled={busy || !folderForm.name.trim()}>{t("Guardar carpeta")}</button></div></form>, () => setFolderForm(null))}
    {folderDeleting && modal(t("Eliminar carpeta"), <><p>{t("Se eliminará")} <strong>«{folderDeleting.name}»</strong>. {t("Sus documentos pasarán a «Sin carpeta» y conservarán su contenido e historial.")}</p><div className="modal-actions"><button className="secondary" disabled={busy} onClick={() => setFolderDeleting(null)}>{t("Cancelar")}</button><button className="danger" disabled={busy} onClick={() => void perform(async () => { await onFolderDelete(folderDeleting); setFolderDeleting(null); setSelected("unfiled"); })}>{t("Eliminar carpeta")}</button></div></>, () => setFolderDeleting(null))}
  </main>;
}
